logging.file: ./logs/position_price_service.log

logging:
  file:
    max-history: 21

position:
  price:
    queue: COM.PROJECT.POSITION.PRICE.RYAN4.QUEUE
  
---
spring:
  profiles: test
  
position:
  price:
    notification:
      sendTo: test@testserver.com

---
spring:
  profiles: dev, default
  
position:
    notification:
      sendTo: dev@devserver.com
---
spring:
  profiles: qa
  
position:
    notification:
      sendTo: qa@qaserver.com
---
spring:
  profiles: prod
  
position:
    notification:
      sendTo: prod@prodserver.com
